### ISSUE TITLE
关于评价指标F1

### ISSUE THREAD

**Issue by WesternTrail** [silence-tang/DASNet-V2#4]
作者你好，今天把你代码基本都看了一遍。但是我并没有看DASNet的原始代码，我发现代码中F1的计算是根据不同的thresh确定的。好像从0-2.多选取了96个阈值。得到在每个阈值下的precision,recall和F1。最后找一个使得F1值最大的作为阈值。这种方式我也是第一次看到，之前的看的一些基于distance map的方式一般都是设置阈值为1，然后判断是否changed。你怎么看这种评估方式？？？

**Comment by silence-tang** [comment]
我这也是按照DASNet的原始代码来的，作者应该是想用max f1-score作为选取最佳模型的标准（某种程度上和area under the curve等价）。从0-2选是因为distance map各元素的取值范围似乎是0-2，这个我已经记不太清了。

如果是要前向推理（假设模型已经训练完毕），直接得到01二值图，确实需要事先指定一个阈值，但这里的阈值和训练的时候的那96个阈值不是一个概念。在这里，阈值是根据模型的max f1-score对应的阈值来选取的。比如：假设训练到最后，模型的max f1-score为0.96，对应的阈值为1.2，那么我们在前向推理时设定的阈值就取1.2。

**Comment by WesternTrail** [comment]
好的感谢！我懂了，本身他也是把阈值看作一个可以调参的量了，其实也是个trick
